INSERT INTO services (name, price) VALUES ('Dog Vaccination Package',65.00);
INSERT INTO services (name, price) VALUES ('Cat Vaccination Package',55.00);
INSERT INTO services (name, price) VALUES ('Rabies 1 or 3 year Vaccination',18.00);
INSERT INTO services (name, price) VALUES ('Parasite Treatment Package',75.00);
INSERT INTO services (name, price) VALUES ('Microchip Service',15.00);
INSERT INTO services (name, price) VALUES ('Basic Teeth Cleaning and Exam',100.00);
INSERT INTO services (name, price) VALUES ('Strong Joints Dog Supplement',5.87);
INSERT INTO services (name, price) VALUES ('Healthy Coat Dog Supplement',6.44);
INSERT INTO services (name, price) VALUES ('Probiotic Dog Treats',8.89);
INSERT INTO services (name, price) VALUES ('Small Hypoallergenic Pet Bowl',6.55);
INSERT INTO services (name, price) VALUES ('Large Hypoallergenic Pet Bowl',8.14);
INSERT INTO services (name, price) VALUES ('Cat Hairball Remedy Gel',6.00);
INSERT INTO services (name, price) VALUES ('Probiotic Cat Treats',7.89);
INSERT INTO services (name, price) VALUES ('Here Kitty Kitty Organic Catnip',7.75);
INSERT INTO services (name, price) VALUES ('Calm Cat Anxiety Relief Spray',9.49);
INSERT INTO services (name, price) VALUES ('Medicated Dog Shampoo',8.73);
INSERT INTO services (name, price) VALUES ('Strong Joints Cat Supplement',5.53);
INSERT INTO services (name, price) VALUES ('Healthy Coat Cat Supplement',9.56);
INSERT INTO services (name, price) VALUES ('Senior Dog Vitamin Chews',9.66);
INSERT INTO services (name, price) VALUES ('Kidney Support Liquid Dietary Supplement',9.12);
INSERT INTO services (name, price) VALUES ('Advance Pet Oral Care Toothbrush and Toothpaste',9.55);

INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Cally','Reynolds','penatibus.et@lectusa.com','(901) 166-8355','556 Lakewood Park, Bismarck, ND 58505');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Sydney','Bartlett','nibh@ultricesposuere.edu','(982) 231-7357','4829 Badeau Parkway, Chattanooga, TN 37405');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Hunter','Newton','quam.quis.diam@facilisisfacilisis.org','(831) 996-1240','2 Rockefeller Avenue, Waco, TX 76796');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Brooke','Perkins','sit@vitaealiquetnec.net','(340) 732-9367','87 Brentwood Park, Dallas, TX 75358');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Nolan','Slater','sociis.natoque.penatibus@pedeCras.co.uk','(540) 487-5928','99 Sage Street, Reno, NV 89505');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Germaine','Green','ultrices.Vivamus@orciin.edu','(466) 455-4160','6 Jana Park, San Antonio, TX 78240');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Medge','Ratliff','nulla.ante@posuerevulputate.org','(358) 751-8227','75 Erie Terrace, Dayton, OH 45454');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Nash','Vasquez','ut.nisi@elitAliquam.ca','(989) 937-6199','39464 Debra Lane, Young America, MN 55557');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Michael','Rutledge','eget.lacus@sitametorci.org','(366) 822-4574','8231 Crowley Crossing, Cincinnati, OH 45999');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Guy','Ochoa','montes.nascetur@semperrutrum.net','(720) 242-4596','92483 Doe Crossing Drive, Lansing, MI 48956');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Coby','Lucas','auctor.odio@utdolordapibus.co.uk','(177) 816-3420','7316 Dryden Road, Memphis, TN 38114');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Merrill','Freeman','pellentesque@Donecest.net','(838) 734-1768','7746 Mitchell Point, New Haven, CT 6510');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Rae','Hawkins','et.magnis@posuereat.edu','(484) 158-4493','181 Packers Way, Boston, MA 2216');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Sade','Santiago','ipsum@eu.co.uk','(497) 492-4618','2 Farragut Crossing, Anchorage, AK 99512');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Judith','Leonard','Ut.tincidunt.vehicula@urnajusto.org','(549) 439-1744','2 Namekagon Trail, Trenton, NJ 8619');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Malik','Faulkner','Nullam.suscipit.est@ametornare.com','(186) 520-2519','8 Gerald Point, Orlando, FL 32868');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Benjamin','Miranda','Proin.vel.nisl@enim.ca','(992) 329-4925','40 Lighthouse Bay Circle, Saint Petersburg, FL 33731');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Rhona','Stanley','metus@dictumplacerataugue.net','(237) 294-5071','992 Haas Avenue, San Diego, CA 92186');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Amena','Petersen','amet.massa@Maurisvestibulumneque.net','(383) 554-7219','6625 Lukken Circle, Brooklyn, NY 11205');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Lucas','Trevino','eros@faucibusleo.ca','(176) 773-9482','78 Summer Ridge Alley, Duluth, MN 55805');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Dorian','Dale','adipiscing.elit.Etiam@euultricessit.edu','(311) 929-6026','9843 Graceland Point, Lansing, MI 48930');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Shellie','Velez','dignissim.tempor@tincidunt.edu','(197) 282-8671','5204 Beilfuss Place, Columbus, OH 43204');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Rhonda','Wilder','sed@quispedePraesent.edu','(653) 854-3876','92 Northfield Terrace, Louisville, KY 40287');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Tyrone','Powell','Nullam.ut@tellusjusto.co.uk','(113) 724-9255','91955 Mosinee Parkway, Indianapolis, IN 46278');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Raja','Wells','arcu.eu@eusem.com','(244) 178-1821','62 Warner Place, Washington, DC 20525');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Adara','Langley','per.conubia.nostra@neque.org','(696) 810-8990','88 Burning Wood Junction, Anaheim, CA 92812');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Jerry','Gill','taciti@vehicula.edu','(491) 955-1047','229 Golden Leaf Road, Gadsden, AL 35905');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Arden','Bennett','congue.a@lorem.edu','(959) 194-1875','6502 Montana Junction, New Orleans, LA 70174');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Philip','Ware','faucibus.Morbi@semmagna.org','(615) 720-3672','58034 Nelson Street, Washington, DC 20036');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Clementine','Oliver','purus@luctus.edu','(603) 332-7827','6 Granby Drive, Topeka, KS 66606');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Iliana','Hester','mauris@consectetuerrhoncus.ca','(716) 866-7734','3409 Oriole Point, Peoria, IL 61629');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Francesca','Hodges','tempor.arcu.Vestibulum@tinciduntaliquamarcu.com','(324) 686-7614','609 Everett Avenue, Des Moines, IA 50330');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Sydney','Robertson','tempor.arcu@ascelerisque.com','(304) 577-5758','3061 Sachs Lane, Scottsdale, AZ 85255');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Amery','Washington','Suspendisse.commodo@egestasrhoncus.ca','(191) 476-0002','710 Old Gate Circle, Chicago, IL 60641');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Barrett','Howell','ultricies.ornare.elit@Mauris.ca','(538) 115-5665','0864 Bluestem Center, Sacramento, CA 95823');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Lunea','Rios','nisl.Maecenas.malesuada@nuncac.org','(311) 982-5690','289 Porter Crossing, Silver Spring, MD 20918');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Wynter','Roberts','ac@Utsemper.net','(721) 262-6519','89318 Heffernan Crossing, Santa Barbara, CA 93150');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Melyssa','Gates','ipsum.cursus.vestibulum@semperegestas.com','(263) 976-2589','419 Tennyson Court, San Luis Obispo, CA 93407');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Quail','Vance','Mauris@Proin.co.uk','(229) 484-5107','25 Green Plaza, Davenport, IA 52804');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Rose','Holcomb','sagittis.placerat.Cras@pharetra.edu','(129) 823-5800','6755 Burrows Center, Columbus, GA 31914');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Ayanna','Foreman','molestie@mattis.edu','(146) 146-9356','30 Gulseth Junction, San Francisco, CA 94154');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Jael','Rice','at.auctor@nonvestibulumnec.net','(394) 444-6027','68316 Emmet Trail, San Diego, CA 92153');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Anastasia','Owens','egestas.a@sapien.edu','(423) 401-3016','86432 Westridge Alley, Wichita, KS 67230');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Zephr','Mcgee','nec@orci.ca','(708) 764-4578','2 Nevada Junction, Pittsburgh, PA 15235');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Roth','Black','luctus@nec.co.uk','(330) 983-4433','605 Bunting Road, White Plains, NY 10606');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Calvin','Henry','blandit@quis.com','(327) 821-0113','52 Sachtjen Avenue, Tampa, FL 33661');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Joshua','Delaney','Proin@vitaeerat.co.uk','(838) 282-2276','62 Karstens Junction, Tulsa, OK 74141');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Laith','Jordan','ligula.tortor@Curabituregestas.co.uk','(868) 659-6715','7468 Talmadge Junction, Baltimore, MD 21275');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Blaine','Ashley','amet.consectetuer.adipiscing@vestibulum.com','(261) 759-5806','561 Basil Court, Greensboro, NC 27404');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Mollie','Meyers','eu.odio@tempor.edu','(309) 329-9140','4276 Hallows Terrace, San Antonio, TX 78260');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Oleg','Merritt','Vestibulum.ante.ipsum@sapienimperdiet.edu','(513) 912-4721','874 Leroy Hill, Santa Rosa, CA 95405');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Zephr','Fry','a@nibhdolor.com','(166) 472-2547','6 Manitowish Trail, Topeka, KS 66642');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Nolan','Robertson','neque.sed@turpis.ca','(822) 296-4465','8698 Crest Line Parkway, Columbia, SC 29208');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Astra','Edwards','Aliquam.fringilla.cursus@necmalesuada.org','(177) 600-1729','5733 Walton Center, Jamaica, NY 11470');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Adena','Jenkins','in@dictum.org','(342) 731-9079','22577 Starling Lane, Chicago, IL 60604');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Sasha','King','ac.mattis@pretiumaliquet.net','(733) 104-5058','86073 Sloan Way, Pueblo, CO 81015');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Kenneth','Potts','nec.ante@Donecnibhenim.edu','(976) 544-1168','1 Springview Circle, Helena, MT 59623');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Roanna','Acevedo','sit@ac.org','(868) 464-7466','7 Cottonwood Plaza, Pensacola, FL 32505');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Debra','Finley','arcu@nisiMaurisnulla.co.uk','(542) 954-1230','3627 Pine View Circle, Cleveland, OH 44118');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Shay','Davidson','tempus.scelerisque@turpisnonenim.co.uk','(934) 777-4129','423 Kenwood Park, Temple, TX 76505');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Kyla','Hebert','vitae.nibh.Donec@ideratEtiam.org','(715) 654-8147','4 Manufacturers Pass, Greensboro, NC 27499');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Josiah','Wagner','orci.luctus@semut.org','(700) 742-7671','58 Melvin Pass, Huntsville, AL 35815');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Hadley','Sosa','convallis.convallis.dolor@aenim.co.uk','(222) 150-9436','95567 Browning Crossing, Vero Beach, FL 32964');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Karly','Hardin','ipsum.Suspendisse@euerosNam.ca','(106) 281-7513','9776 Beilfuss Parkway, Cleveland, OH 44118');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Molly','Grant','mauris.erat@cursusdiamat.net','(689) 843-0460','791 Cherokee Court, Merrifield, VA 22119');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Jaime','Craig','rhoncus@facilisis.co.uk','(375) 915-2089','7189 Pankratz Point, Dayton, OH 45454');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Wesley','Rush','massa.Mauris.vestibulum@In.co.uk','(722) 576-0563','24812 Cordelia Trail, Corpus Christi, TX 78475');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Dustin','Daugherty','neque.sed@ultriciessemmagna.ca','(951) 720-1227','207 Bunting Street, Sioux City, IA 51105');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Kyle','Keith','arcu.Morbi@ut.co.uk','(578) 125-5684','795 Troy Terrace, Atlanta, GA 31106');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Chester','Best','felis@eros.net','(608) 587-5791','102 Fallview Terrace, Minneapolis, MN 55441');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Kaden','Sharpe','a@Incondimentum.org','(246) 987-2818','99 Hanson Way, Richmond, VA 23242');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Shafira','Bennett','nascetur@sitametmetus.org','(279) 911-0843','9 Roth Place, Dayton, OH 45454');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Zena','Washington','risus@ProindolorNulla.edu','(921) 805-5150','823 Glacier Hill Point, San Bernardino, CA 92415');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Eric','Donaldson','ante.ipsum.primis@gravidasagittis.com','(714) 520-4254','62597 Lighthouse Bay Drive, Port Charlotte, FL 33954');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Indira','Odom','Etiam@nisi.ca','(714) 947-5101','2 Hovde Plaza, Saint Paul, MN 55108');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Savannah','Conner','Morbi.sit@pedemalesuada.net','(361) 128-7285','52509 Almo Lane, Raleigh, NC 27658');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Graham','Frederick','risus.at@orci.co.uk','(707) 474-5854','22 Superior Way, Boston, MA 2203');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Chastity','Charles','in.felis@Mauriseu.co.uk','(186) 176-2590','22278 Waubesa Road, Birmingham, AL 35225');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Leslie','Pace','Vivamus.nisi@risus.com','(623) 686-1821','839 Pepper Wood Street, El Paso, TX 88563');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Nasim','Sheppard','ut@ultricessit.co.uk','(930) 295-6752','5 Melvin Street, New York City, NY 10039');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Yoko','Travis','scelerisque.neque.sed@atlacus.net','(818) 864-3843','3149 Kinsman Court, Winston Salem, NC 27116');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Brody','Love','et.malesuada@consequat.net','(360) 338-4848','96 Eliot Way, Fresno, CA 93715');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Mona','Matthews','Donec.nibh.enim@pede.co.uk','(723) 808-1834','32174 Ridge Oak Plaza, San Francisco, CA 94177');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Jenna','Hendricks','purus.Nullam.scelerisque@ligula.net','(840) 746-9696','33837 Independence Place, Oklahoma City, OK 73124');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Sydney','Dejesus','mattis.velit@vel.net','(110) 771-1999','3 Morning Circle, San Francisco, CA 94177');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Hedy','Vang','cursus.et.eros@loremfringilla.ca','(383) 134-3234','1876 Petterle Court, Brea, CA 92822');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Gray','Gutierrez','ullamcorper@tempusrisus.edu','(496) 849-2265','7271 Ramsey Way, Washington, DC 20420');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Cailin','Alford','gravida.sit@miAliquam.net','(368) 400-8301','282 Acker Terrace, Winston Salem, NC 27157');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Erasmus','Neal','dolor@perconubia.edu','(774) 548-5638','907 Briar Crest Terrace, Santa Barbara, CA 93150');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Derek','Conrad','arcu@elit.ca','(275) 477-2907','6 Carioca Crossing, Arvada, CO 80005');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Melinda','Price','fringilla@Nulla.net','(748) 701-8010','318 Park Meadow Hill, San Antonio, TX 78285');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Rebekah','Nelson','pretium.et@egestaslacinia.ca','(447) 121-6473','8117 Straubel Plaza, Jamaica, NY 11480');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Ronan','Mendez','risus@feugiatnonlobortis.co.uk','(302) 847-0643','3849 Northport Parkway, Appleton, WI 54915');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Brock','Case','magna.Phasellus@Phasellus.net','(544) 534-1984','602 Sommers Parkway, Norfolk, VA 23520');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Theodore','Brock','feugiat@Aliquameratvolutpat.edu','(662) 476-0315','400 Summit Lane, Brooklyn, NY 11210');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Serena','Malone','dictum@Fuscefermentumfermentum.edu','(137) 440-1643','30 Onsgard Crossing, Los Angeles, CA 90040');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Eagan','Bray','Vestibulum.ante@sitametmassa.net','(529) 738-3373','55617 Straubel Drive, Philadelphia, PA 19146');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Nicole','Mcconnell','enim.Mauris.quis@Vivamusnibh.net','(892) 616-0264','8 Delaware Hill, Garden Grove, CA 92844');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Kamal','Newton','turpis@loremvehicula.com','(704) 685-9968','718 Lakewood Parkway, Appleton, WI 54915');
INSERT INTO customers (first_name, last_name, email, phone, address) Values ('Quentin','Marshall','velit@Pellentesquehabitantmorbi.org','(203) 755-9348','100 Bunting Drive, Washington, DC 20557');

INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Edgepulse','Gerald Martinez','(991) 321-6632','gmartinez0@hostgator.com','900 Butternut Avenue, Albany, NY 12242');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Jabbersphere','Victor Harrison','(404) 940-2991','vharrison1@geocities.com','684 Express Avenue, Houston, TX 77070');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Quaxo','Jimmy Ford','(960) 473-6813','jford2@nyu.edu','7 Sheridan Plaza, Lubbock, TX 79491');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Yakijo','Kenneth Miller','(282) 524-5773','kmiller3@alibaba.com','56 Sunbrook Terrace, Metairie, LA 70033');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Omba','Jennifer Peterson','(376) 185-7734','jpeterson4@homestead.com','7817 Carpenter Lane, Charlottesville, VA 22903');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Mycat','Jeffrey Williams','(924) 896-3371','jwilliams5@state.gov','40693 Florence Park, Salt Lake City, UT 84115');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Babbleopia','Katherine Gibson','(999) 216-7704','kgibson6@miitbeian.gov.cn','1 Ilene Crossing, Memphis, TN 38126');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Tavu','Bonnie Peters','(841) 046-3262','bpeters7@ebay.co.uk','6 Little Fleur Drive, Asheville, NC 28815');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Yotz','Arthur Bryant','(753) 980-5495','abryant8@adobe.com','194 David Place, North Little Rock, AR 72118');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Realbuzz','Julie Daniels','(988) 704-8409','jdaniels9@netlog.com','41 Evergreen Point, Huntsville, AL 35815');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Talane','Doris Banks','(638) 639-1027','dbanksa@discovery.com','1 Montana Trail, Seattle, WA 98133');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Skaboo','Justin Lawrence','(883) 939-1134','jlawrenceb@patch.com','553 Coolidge Drive, Charlotte, NC 28242');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Chatterpoint','Elizabeth Chapman','(477) 406-4840','echapmanc@ftc.gov','29 Cody Pass, Washington, DC 20231');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('InnoZ','Robin Gardner','(849) 295-8639','rgardnerd@ftc.gov','2172 Moose Avenue, Champaign, IL 61825');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Voonyx','Jonathan Murray','(395) 210-5149','jmurraye@paginegialle.it','334 Hoard Parkway, Alhambra, CA 91841');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Topicware','Kathleen Young','(128) 795-1428','kyoungf@histats.com','534 Union Lane, Pittsburgh, PA 15225');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Browsezoom','Terry Carter','(641) 254-3654','tcarterg@shareasale.com','23 Hudson Center, Washington, DC 20530');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Jetwire','Ralph Robinson','(169) 278-8061','rrobinsonh@uol.com.br','337 Anderson Terrace, El Paso, TX 88514');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Babbleblab','Wayne Rose','(676) 164-7258','wrosei@unc.edu','5863 Cody Alley, Fort Wayne, IN 46852');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Jabbersphere','Jennifer Simpson','(797) 876-7026','jsimpsonj@google.com.br','595 Glacier Hill Way, Tulsa, OK 74133');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Wikivu','Mildred Peterson','(551) 438-8253','mpetersonk@census.gov','7575 Stone Corner Street, El Paso, TX 79989');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Innojam','Phillip Kim','(441) 924-6526','pkiml@list-manage.com','61 Bartelt Road, New York City, NY 10105');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Yadel','Shirley Gutierrez','(290) 361-9481','sgutierrezm@mtv.com','97 Park Meadow Hill, Richmond, VA 23203');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('DabZ','Irene Peters','(192) 180-2622','ipetersn@patch.com','2 Ryan Avenue, Columbia, SC 29203');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Edgeclub','Margaret Reynolds','(838) 987-7597','mreynoldso@mapquest.com','41 Butternut Way, Tucson, AZ 85737');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Feedbug','Christina Dean','(394) 466-6734','cdeanp@ed.gov','13 Forest Dale Place, Farmington, MI 48335');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Chatterpoint','Martha Riley','(450) 459-4457','mrileyq@hostgator.com','76 Lakewood Road, Eugene, OR 97405');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Ooba','Ashley Ford','(158) 355-6858','afordr@simplemachines.org','422 Harper Junction, Lake Worth, FL 33467');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Kazio','Samuel Hicks','(521) 554-5962','shickss@edublogs.org','128 Northview Trail, Beaverton, OR 97075');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Fatz','Justin Murphy','(951) 192-3333','jmurphyt@php.net','3639 Tennessee Way, Mobile, AL 36689');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Edgetag','Michael Cruz','(031) 548-0943','mcruzu@telegraph.co.uk','3 Texas Way, Trenton, NJ 8638');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Rhycero','Christine Welch','(592) 770-9160','cwelchv@dagondesign.com','3 Luster Road, Shawnee Mission, KS 66220');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Linklinks','Betty Hunt','(427) 915-4138','bhuntw@mayoclinic.com','10 Crownhardt Center, Denver, CO 80223');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Skippad','Rachel King','(798) 340-4834','rkingx@baidu.com','63 Scott Road, New Haven, CT 6538');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Oyoloo','Richard Richardson','(267) 043-5096','rrichardsony@squarespace.com','7941 Cottonwood Plaza, Baltimore, MD 21282');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Dabfeed','Dennis Perkins','(470) 411-0744','dperkinsz@shutterfly.com','25331 Florence Court, Young America, MN 55564');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Rooxo','Andrea Stephens','(030) 069-4355','astephens10@csmonitor.com','22 Reinke Terrace, Indianapolis, IN 46231');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Rhynyx','Raymond Long','(333) 716-1970','rlong11@japanpost.jp','3 Ridgeview Park, Arlington, VA 22217');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Tavu','Jose Johnson','(349) 112-3689','jjohnson12@epa.gov','91 Laurel Park, Huntsville, AL 35810');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('LivePet','Theresa Berry','(347) 985-0405','tberry13@tiny.cc','7502 Riverside Crossing, Wilmington, DE 19886');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Jaloo','Bonnie Roberts','(748) 268-7532','broberts14@hubpages.com','7 Farmco Court, Montgomery, AL 36125');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Kazu','Christina Mendoza','(529) 838-0755','cmendoza15@google.pl','54 Luster Park, Des Moines, IA 50369');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Photolist','Raymond Stephens','(558) 050-0005','rstephens16@vkontakte.ru','45 Homewood Park, Charlotte, NC 28215');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Yambee','Nicole Gibson','(041) 696-5870','ngibson17@weibo.com','8704 Washington Junction, Clearwater, FL 34615');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Abata','Shawn Barnes','(959) 677-9827','sbarnes18@europa.eu','5 5th Street, Sioux Falls, SD 57110');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Voonder','Denise Johnston','(144) 408-8407','djohnston19@google.ca','29 Arapahoe Lane, Denver, CO 80291');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Vidoo','Mildred Gibson','(477) 696-8483','mgibson1a@behance.net','50137 Oakridge Pass, Conroe, TX 77305');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Gabtune','Randy Myers','(341) 210-0999','rmyers1b@wunderground.com','383 Gale Lane, Irvine, CA 92717');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Blognation','James Collins','(398) 763-8862','jcollins1c@businesswire.com','2 Anniversary Center, Oklahoma City, OK 73129');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Centizu','Roger Fuller','(540) 724-7142','rfuller1d@meetup.com','93214 Emmet Hill, Portland, OR 97216');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Leexo','Aaron Gutierrez','(358) 527-3469','agutierrez1e@theatlantic.com','92 Drewry Avenue, Wichita, KS 67230');
INSERT INTO vendors (name, contact, phone, email, address) VALUES ('Yakitri','Roy Wood','(699) 388-0362','rwood1f@tinypic.com','4 Dakota Alley, Stockton, CA 95219');
