name: Main Workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
    tags-ignore:
      - v*

jobs:
  build-test-release:
    name: Build, test, and release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.MY_GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      #- name: Auto-version
      #  id: auto-version
      #  uses: nadeeshi/quarkus-basic/auto-version-action@v1.0.0
      #  with:
      #    github-token: ${{secrets.MY_GITHUB_TOKEN}}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Test and Build
        run: ./mvnw --batch-mode clean verify -Drevision=${{ steps.auto-version.outputs.auto-version }}

      # https://github.com/rymndhng/release-on-push-action
      - id: create-release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch

      - name: Build docker images
        run: |
          ./mvnw --batch-mode package -Dquarkus.container-image.build=true -Drevision=${{ steps.auto-version.outputs.auto-version }}
          docker build -t ${{ secrets.CONTAINER_IMAGE_REGISTRY }}/${{ secrets.CONTAINER_IMAGE_GROUP }}/quarkus-basic:latest .
        env:
          QUARKUS_CONTAINER_IMAGE_GROUP: ${{ vars.CONTAINER_IMAGE_GROUP }}
          QUARKUS_CONTAINER_IMAGE_REGISTRY: ${{ vars.CONTAINER_IMAGE_REGISTRY }}
          QUARKUS_CONTAINER_IMAGE_TAG: ${{ steps.create-release.outputs.version }}
          QUARKUS_CONTAINER_IMAGE_ADDITIONAL_TAGS: latest

      - name: List Docker images
        run: docker images

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Release
        run: |
          echo "Pushing image to ECR..."
          docker tag ${{ vars.CONTAINER_IMAGE_REGISTRY }}/${{ vars.CONTAINER_IMAGE_GROUP }}/quarkus-basic:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com/nrapp/nr-backend/quarkus-basic:latest
          docker push ${{ vars.CONTAINER_IMAGE_REGISTRY }}/${{ vars.CONTAINER_IMAGE_GROUP }}/quarkus-basic --all-tags
         
         
