name: PR Workflow

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'readme.md'

jobs:
  build-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job was automatically triggered by PR workflow event"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: echo "This repository has been cloned to the runner"
      #- name: Auto-version
      #  id: auto-version
      #  uses: nadeeshi/quarkus-basic/auto-version-action@v1.0.0
      #  with:
      #    github-token: ${{secrets.MY_GITHUB_TOKEN}}
      - run: echo "Version has updated"
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - run: echo "start test your code on the runner"
      - name: Test and Build
        run: ./mvnw --batch-mode clean verify -Drevision=${{ steps.auto-version.outputs.auto-version }}