name: PR Workflow

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'readme.md'

# use - keyword specified an action that job will run (either predefined action from GitHub Marketplace or customized one)
# GitHub Secrets and variables allow us to manage reusable configuration data
# @v3 - means the version of the action (version tag)
jobs:
  build-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job was automatically triggered by PR workflow event"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: echo "This repository has been cloned to the runner"

      # This job will handle versioning for this repository, but it from another custom repository
      # This job use access token with GitHub Actions secret to access our repositories
      #- name: Auto-version
      #  id: auto-version
      #  uses: nadeeshi/quarkus-basic/auto-version-action@v1.0.0
      #  with:
      #    GITHUB_TOKEN: ${{secrets.MY_GITHUB_TOKEN}}
      - run: echo "Version has updated"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - run: echo "start test your code on the runner"

      - name: Test and Build
        run: ./mvnw --batch-mode clean verify -Drevision=${{ steps.auto-version.outputs.auto-version }}